name: "Issue Labeler"

on:
  issues:
    types: [opened, edited, reopened]
  workflow_call:

permissions:
  contents: read
  issues: write

jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/issue-labeler.yml
        not-before: 2025-10-01T00:00:00Z
        enable-versioned-regex: 0